server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update # se crean las tablas de forma automatica atravez de la entidad
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # lenguaje que utiliza para convertir los objetos en sql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #clase que viene con el driver de mysql 
    url: jdbc:mysql://localhost:3306/products?zeroDateTimeBehavior=convertToNull&serverTimeZone=UTC
    username: root
    password: 
 
  
  
#podemos hacer distintos cambios de la configuracion de nuestro proyecto
#cambiar el puerto
#server.port = 8080 
#modificar algo del loggin, por ejemplo el nivel de manejo de loggin
#loggin.level.root =INFO
#ponemos el paquete al nivel de debug
#loggin.level.com.estudio=DEBUG
#modificamos el formato de fecha
#logging.pattern.dateformat=hh:mm